# pylint: disable=C0103
"""Generated by Django 4.1 on 2022-11-18 09:34"""

from django.db import migrations, models


class Migration(migrations.Migration):
    """Migrations"""

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Livro",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.TextField()),
                ("data", models.TextField()),
                ("highlight", models.TextField()),
            ],
        ),
    ]
