# pylint: disable=C0103
"""Generated by Django 4.1 on 2022-12-16 14:55"""

from django.db import migrations, models


class Migration(migrations.Migration):
    """Migrations"""

    dependencies = [
        ("core", "0002_livro"),
    ]

    operations = [
        migrations.AlterField(
            model_name="livro",
            name="titulo",
            field=models.TextField(max_length=500),
        ),
    ]
