# pylint: disable=C0103
"""Migrations"""
# Generated by Django 4.1 on 2022-12-17 20:41

from django.db import migrations, models


class Migration(migrations.Migration):
    """Migrations"""

    dependencies = [
        ("core", "0003_alter_livro_titulo"),
    ]

    operations = [
        migrations.AddField(
            model_name="livro",
            name="anotacao",
            field=models.TextField(null=True),
        ),
    ]
