name: Django Testes

on:
  push:
    branches:
      -main
  
  pull_request:
    branches:
      -main
 
jobs:
  build:
    runs-on: ubuntu-latest
    step:
    - uses: actions/checkout@v2
    - name: Set up Python 3.10
      uses: action/setup-python@v2]
      with:
        python-version: 3.10
